import  {StyleSheet}  from "@react-pdf/renderer";
export const styles = StyleSheet.create({
  page: {
    padding: "30px 40px",
    fontSize: 12,
    backgroundColor: "#ffffff",
    fontFamily: "Helvetica",
    lineHeight: 1.4,
  },
  header: {
    fontSize: 20,
    fontWeight: 700,
    marginBottom: 20,
    color: "#2c3e50",
  },
  underlinedText: {
    textDecoration: "underline",
    fontSize: 20,
    fontWeight: 700,
    color: "#2c3e50",
  },
  boldText: {
    fontSize: 13,
    fontWeight: 600,
    color: "#34495e",
  },
  spaceY: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  normalText: {
    fontSize: 10,
    fontWeight: "normal",
    color: "#7f8c8d",
  },
  businessInfo: {
    fontSize: 12,
    fontWeight: 600,
    color: "#2c3e50",
    lineHeight: 1.3,
  },
  contactInfo: {
    fontSize: 10,
    color: "#7f8c8d",
    lineHeight: 1.3,
  },
  paymentDetails: {
    marginTop: 15,
    fontSize: 11,
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },

  invoiceDetails: {
    marginTop: 20,
    fontSize: 12,
    display: "flex",
    flexDirection: "column",
    gap: 10,
    alignItems: "flex-end",
  },

  
  boxContainer: {
    border: "1px solid #bdc3c7",
    padding: 8,
    width: 120,
    backgroundColor: "#f8f9fa",
    borderRadius: 2,
  },

  boxLabel: {
    fontSize: 12,
    fontWeight: 600,
    marginBottom: 5,
    color: "#2c3e50",
  },
  boxValue: {
    fontSize: 12,
    fontWeight: "normal",
    color: "#34495e",
  },
  largeBox: {
    minHeight: 100,
    width: 200,
  },

 
  table: {
    display: "table",
    width: "100%",
    marginTop: 25,
    borderStyle: "solid",
    borderWidth: 1,
    borderColor: "#bdc3c7",
    borderRadius: 4,
    borderCollapse: "collapse",
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#34495e",
    borderBottomWidth: 1,
    borderColor: "#2c3e50",
  },
  tableHeaderCell: {
    textAlign: "center",
    fontWeight: 700,
    borderRightWidth: 1,
    borderColor: "#2c3e50",
    padding: "12px 8px",
    color: "#ffffff",
    fontSize: 10,
    lineHeight: 1.2,
    minHeight: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  row: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderColor: "#ecf0f1",
    backgroundColor: "#ffffff",
    minHeight: 35,
  },
  cell: {
    textAlign: "center",
    padding: "10px 6px",
    fontSize: 9,
    color: "#34495e",
    borderRightWidth: 1,
    borderColor: "#ecf0f1",
    lineHeight: 1.3,
    justifyContent: "center",
    alignItems: "center",
    wordWrap: "break-word",
  },
  parent: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  totalSection: {
    width: "100%",
    border: "1px solid #bdc3c7",
    padding: 20,
    marginTop: 25,
    backgroundColor: "#f8f9fa",
    borderRadius: 4,
  },
  vatNotice: {
    fontSize: 10,
    color: "#34495e",
    lineHeight: 1.4,
    fontWeight: 500,
    marginBottom: 3,
  },
  totalRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    justifyContent: "space-between",
  },
  totalLabel: {
    fontSize: 11,
    fontWeight: 600,
    color: "#2c3e50",
    minWidth: 80,
  },
  totalBox: {
    border: "1px solid #bdc3c7",
    padding: "8px 12px",
    minWidth: 100,
    backgroundColor: "#ffffff",
    borderRadius: 2,
  },
  totalValue: {
    fontSize: 11,
    fontWeight: 600,
    color: "#2c3e50",
    textAlign: "center",
  },
});